# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://andy.kitchen/
# baseurl: /blog
title: Andy Kitchen
author: Andy Kitchen
description: Personal site
avatar: profile.jpg
email: kitchen.andy@gmail.com
github: andykitchen # username
twitter: auastro

# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
